name: 'transitclock'
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
      target: core
    volumes:
      - ./configs:/usr/local/transitclock/config
      - ./logs:/usr/local/transitclock/logs
    command: core
    links:
      - database

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    volumes:
      - ./configs:/usr/local/transitclock/config
      - ./web-logs:/Logs
      - ./tomcat-logs:/usr/local/tomcat/logs
    command: catalina
    ports:
      - "8080:8080"
    links:
      - core
      - database

  database:
    image: postgres
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=p4ssword!
